language: scala
sudo: false
cache:
  directories:
    - $HOME/.ivy2
matrix:
  include:
    - jdk: oraclejdk8
      scala: 2.10.5
script:
  - sbt ++$TRAVIS_SCALA_VERSION coverage test
after_success:
  - bash < (curl -s https://codecov.io/bash)
